// generated by deepseek
"use client";

import React, { useState } from "react";
import { Controller } from "react-hook-form";
import { Column } from "../layouts/column";
import { ErrorMessageLabel } from "./errorMessageLabel";

export function ControlledStarRating({ fieldName }: { fieldName: string }) {
  return (
    <Column className="gap-y-2">
      <Controller
        rules={{ required: true }}
        name={fieldName}
        defaultValue={0}
        render={({ field: { onChange, value } }) => (
          <StarRating onRate={onChange} rating={value} totalStars={5} />
        )}
      />
      <ErrorMessageLabel fieldName={fieldName} />
    </Column>
  );
}

export const StarRating = ({
  totalStars = 5,
  rating = 0,
  onRate,
}: {
  onRate(rate: number): void;
  rating?: number;
  totalStars?: number;
}) => {
  const [hover, setHover] = useState(0);

  const handleClick = (starValue: number) => {
    if (onRate) {
      onRate(starValue);
    }
  };

  const getRatingColor = (currentRating: number) => {
    if (currentRating <= 1.5) return "text-red-500";
    if (currentRating <= 2.5) return "text-orange-500";
    if (currentRating <= 3.5) return "text-yellow-500";
    if (currentRating <= 4.5) return "text-lime-500";
    return "text-green-600";
  };

  const getRatingMessage = (currentRating: number) => {
    if (currentRating === 0) return "No rate";
    if (currentRating <= 1.5) return "So bad 😞";
    if (currentRating <= 2.5) return "Not good 😐";
    if (currentRating <= 3.5) return "Middle 🤔";
    if (currentRating <= 4.5) return "Hmm, Good 😊";
    return "Great 🎉";
  };

  const getBackgroundColor = (currentRating: number) => {
    if (currentRating <= 1.5) return "bg-red-50 border-red-200";
    if (currentRating <= 2.5) return "bg-orange-50 border-orange-200";
    if (currentRating <= 3.5) return "bg-yellow-50 border-yellow-200";
    if (currentRating <= 4.5) return "bg-lime-50 border-lime-200";
    return "bg-green-50 border-green-200";
  };

  const currentRating = hover || rating;
  const ratingColor = getRatingColor(currentRating);
  const ratingMessage = getRatingMessage(rating);
  const bgColor = getBackgroundColor(rating);

  return (
    <div className="flex flex-col items-center gap-4 font-sans">
      <div className="flex gap-1">
        {[...Array(totalStars)].map((_, index) => {
          const starValue = index + 1;
          return (
            <button
              key={index}
              onClick={(e) => {
                e.preventDefault();
                handleClick(starValue);
              }}
              onMouseEnter={() => setHover(starValue)}
              onMouseLeave={() => setHover(0)}
              className="cursor-pointer focus:outline-none transition-all duration-200 hover:scale-110"
              aria-label={`Rate ${starValue} Of ${totalStars}`}
            >
              <svg
                className={`w-8 h-8 md:w-10 md:h-10 transition-all duration-200 ${
                  starValue <= currentRating
                    ? `${ratingColor} drop-shadow-md`
                    : "text-gray-300 dark:text-gray-600"
                }`}
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
            </button>
          );
        })}
      </div>

      {rating > 0 && (
        <div
          className={`${bgColor} border rounded-lg px-4 py-2 transition-all duration-300`}
        >
          <div className="flex items-center gap-3">
            <div className={`text-2xl font-bold ${ratingColor}`}>
              {rating.toFixed(1)}
            </div>
            <Column centerH>
              <div className="text-sm text-gray-700">{ratingMessage}</div>
              <div className="flex gap-0.5">
                {[...Array(Math.floor(rating))].map((_, i) => (
                  <span key={i} className={`${ratingColor}`}>
                    ★
                  </span>
                ))}
              </div>
            </Column>
          </div>
        </div>
      )}

      {rating === 0 && (
        <div className="text-sm text-gray-400 bg-gray-50 rounded-lg px-4 py-2">
          Click for rating
        </div>
      )}
    </div>
  );
};
